### ISSUE TITLE
Edit proposal/board

### ISSUE THREAD

**Issue by minsooerickim** [imrebsw/CS100FINALPROJECT#1]
- missing description of why the project is important/intersting
- lacking description of the project
- needs better formatting 
- remove angle brackets/prompts
- fix column order in kanban board

**Comment by imrebsw** [comment]
Hi @minsooerickim , I apologize for the miscommunication on which Github link is to our project. We realized we needed to create the repository under the Github classroom. This is the link to our actual project proposal: https://github.com/cs100/final-project-cs100-reb-calvin-jina-jeff

**Comment by minsooerickim** [comment]
> Hi @minsooerickim , I apologize for the miscommunication on which Github link is to our project. We realized we needed to create the repository under the Github classroom. This is the link to our actual project proposal: https://github.com/cs100/final-project-cs100-reb-calvin-jina-jeff

okay that's fine. but the points wouldn't change as the updates under github classroom were made after i left the feedback.

**Comment by ghost** [comment]
I believe that all of the requested edits were completed.
